### ISSUE TITLE
origen lint throws error

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen_testers#113]
~~~shell
peologin03:origen_testers $ origen lint

COMPLETE CALL STACK
-------------------
uninitialized constant OrigenTesters::Test::DUT::OrigenARMDebug
/users/user/origen/github/origen_testers/lib/origen_testers/test/dut.rb:14:in `<class:DUT>'
/users/user/origen/github/origen_testers/lib/origen_testers/test/dut.rb:3:in `<module:Test>'
/users/user/origen/github/origen_testers/lib/origen_testers/test/dut.rb:2:in `<module:OrigenTesters>'
/users/user/origen/github/origen_testers/lib/origen_testers/test/dut.rb:1:in `<top (required)>'
/users/user/origen/github/origen_testers/config/boot.rb:5:in `require'
/users/user/origen/github/origen_testers/config/boot.rb:5:in `<top (required)>'
~~~

Any ideas?

**Comment by info-rchitect** [comment]
fixed on 0.19.3
