### ISSUE TITLE
Latest code is failing known good flows

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen_testers#115]
Hi,

I am trying out the latest build and known good flows are now failing.

~~~shell
COMPLETE CALL STACK
-------------------
undefined method `[]' for nil:NilClass
/users/user/origen/ruby/2.3.0/bundler/gems/origen_testers-b55dd9367c3e/lib/origen_testers/smartest_based_tester/base/flow.rb:395:in `generate_flag_name'
/users/user/origen/ruby/2.3.0/bundler/gems/origen_testers-b55dd9367c3e/lib/origen_testers/smartest_based_tester/base/flow.rb:249:in `block in on_if_enabled'
/users/user/origen/ruby/2.3.0/bundler/gems/origen_testers-b55dd9367c3e/lib/origen_testers/smartest_based_tester/base/flow.rb:248:in `each'
/users/user/origen/ruby/2.3.0/bundler/gems/origen_testers-b55dd9367c3e/lib/origen_testers/smartest_based_tester/base/flow.rb:248:in `on_if_enabled'
~~~

A [nil flag variable is being accessed without checking for nil](https://github.com/Origen-SDK/origen_testers/blob/master/lib/origen_testers/smartest_based_tester/base/flow.rb#L396).  The culprit is the [on_if_enabled method](https://github.com/Origen-SDK/origen_testers/blob/master/lib/origen_testers/smartest_based_tester/base/flow.rb#L249).  Not sure how this code ever works as the `flag` variable would always be set to nil wouldn't it?

~~~ruby
        def on_if_enabled(node)
          flag, *nodes = *node
          state = node.type == :if_enabled
          [flag].flatten.each do |f|
            flow_control_variables << generate_flag_name(f)
          end
          on_condition_flag(node, state)
        end
        alias_method :on_unless_enabled, :on_if_enabled
~~~

Setting a break point I see the following:

~~~ruby
    245: def on_if_enabled(node)
    246:   flag, *nodes = *node
    247:   state = node.type == :if_enabled
    248:   [flag].flatten.each do |f|
    249:     binding.pry
 => 250:     flow_control_variables << generate_flag_name(f)
    251:   end
    252:   on_condition_flag(node, state)
    253: end

[1] pry(#<OrigenTesters::SmartestBasedTester::V93K::Flow>)> flag
=> [nil]
[2] pry(#<OrigenTesters::SmartestBasedTester::V93K::Flow>)> nodes
=> [s(:group,
  s(:name, "jtag_tapdance_qnd_charz"),
  s(:test,
    s(:object, <TestSuite: jtag_tapdance__vmin_vddcr_soc>),
    s(:name, "jtag_tapdance__vmin_vddcr_soc"),
    s(:number, 0),
    s(:id, "jtag_tapdance_vmin_vddcr_soc_7D77AAD"),
    s(:on_fail,
      s(:if_flag, "$Alarm",
        s(:render, "multi_bin;")))),
  s(:test,
    s(:object, <TestSuite: jtag_tapdance__vmax_vddcr_soc>),
    s(:name, "jtag_tapdance__vmax_vddcr_soc"),
    s(:number, 0),
    s(:id, "jtag_tapdance_vmax_vddcr_soc_7D77AAD"),
    s(:on_fail,
      s(:if_flag, "$Alarm",
        s(:render, "multi_bin;")))),
  s(:id, "t2_7D77AAD"))]
[3] pry(#<OrigenTesters::SmartestBasedTester::V93K::Flow>)> node
=> s(:if_enabled, [nil],
  s(:group,
    s(:name, "jtag_tapdance_qnd_charz"),
    s(:test,
      s(:object, <TestSuite: jtag_tapdance__vmin_vddcr_soc>),
      s(:name, "jtag_tapdance__vmin_vddcr_soc"),
      s(:number, 0),
      s(:id, "jtag_tapdance_vmin_vddcr_soc_7D77AAD"),
      s(:on_fail,
        s(:if_flag, "$Alarm",
          s(:render, "multi_bin;")))),
    s(:test,
      s(:object, <TestSuite: jtag_tapdance__vmax_vddcr_soc>),
      s(:name, "jtag_tapdance__vmax_vddcr_soc"),
      s(:number, 0),
      s(:id, "jtag_tapdance_vmax_vddcr_soc_7D77AAD"),
      s(:on_fail,
        s(:if_flag, "$Alarm",
          s(:render, "multi_bin;")))),
    s(:id, "t2_7D77AAD")))
~~~

**Comment by ginty** [comment]
It looks like an array is allowed, so this would be valid too `s(:if_enabled, ["some_flag_name"], `.
Don't suppose you can explain that from your application side?

**Comment by info-rchitect** [comment]
@ginty yeah maybe this is related to our app, let me do some digging.  thx for the help.

**Comment by redxeth** [comment]
Hi all-- having this issue (passing nil to `if_enable` method) now on a project after upgrading to latest origen_testers. 

Why is it standard for `if_enable` to not be able to handle nil ?   I would assume it would just report the flow lines without enable words if no enable word given. 

I do see the nice error message now.

**Comment by info-rchitect** [comment]
@redxeth It could never handle nil, the new `origen_testers` just [adds a better error message](https://github.com/Origen-SDK/origen_testers/pull/147).  As you can see that passing nil to the flag methods causes a 'can't dup nil' error message.

**Comment by info-rchitect** [comment]
@redxeth Also, the [docs ](https://origen-sdk.org/origen/guides/program/flowapi/)are pretty clear that flags must be passed as a Symbol or a String.  What is the use case of passing nil?

**Comment by redxeth** [comment]
@info-rchitect yeah but should we change it to be able to handle nil? 

If I have a subflow like this:
~~~ruby
Flow.create do |options|
    if_enable options[:enable]
        <blah>
    end
end
~~~

And the caller doesn't set `options[:enable]`, then in my view the `if_enable` should just handle it.

It works ok if I force `options[enable] = ""`

**Comment by info-rchitect** [comment]
@redxeth Well we would have to change the [AST processor](https://github.com/Origen-SDK/origen_testers/blob/master/lib/origen_testers/atp/processor.rb#L68) to allow it and update the documentation.  Personally i think it is up to the user to protect against passing the wrong type argument to the method.

~~~ruby
Flow.create do |options|
    unless options[:enable].nil?
      if_enable options[:enable]
          <blah>
      end
    end
~~~

**Comment by redxeth** [comment]
Hmm-- I don't agree -- because of the fact we may or not not need to pass in options and we have sub-flows within sub-flows.  

If AST doesn't like nil we can certainly catch it in advance and reassign it to `""`.   It could be a pre-processor to the AST.  I get your thinking to catch bugs, I just dont think not having an option defined is something that should crash a method. 

Just wondering what changed from 0.43.0 and earlier that causes this to be an issue now all of a sudden.

**Comment by info-rchitect** [comment]
@redxeth I think we need more voices here, we may disagree but I am open to finding some solution.

**Comment by redxeth** [comment]
Agreed. ;-)  
Anyway for now I assigned a default empty string for my call above to handle it.

**Comment by arkohler** [comment]
if_enable <flagname> do
  some_block
end

This is basically shorthand for
if <flagname> = TRUE (or 1) do some_block
In the case where <flagname> is nil, you could optimize it to remove the if clause.  The question is whether you would want to always want to execute the block or never execute it.
By setting it to an empty string, I think you're opting for the never case, so the block of code can be removed completely from the AST and flow.
When there is a list of flags, you would remove nil options, and skip the entire block if all flags are nil.

A warning message would be appropriate when the block is being skipped entirely.

**Comment by redxeth** [comment]
Hmm I hadn't thougth about the block skipping case-- I was thinking that if you send a nil or empy string argument that it meant you just wanted that block to run anyway, just not qualified with any enable words.  It's a bit ambiguous the intention. To me it's just a shorthand way of not having to pass `if_enable:` option to each test in the block individually, and so it should work the same way.  

I.e. if you pass it nothing then it runs without any enable word, but it still runs.
